# Generated by Django 5.2.12 on 2026-04-06 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacaotipo',
            options={'verbose_name': 'Tipo da avaliação'},
        ),
        migrations.RemoveField(
            model_name='cursodisciplina',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='curso',
            name='instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.instituicaoensino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursodisciplina',
            name='periodo',
            field=models.CharField(default=1, max_length=2, verbose_name='Período'),
            preserve_default=False,
        ),
    ]
