# Generated by Django 5.2.12 on 2026-04-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursodisciplina',
            name='periodo',
            field=models.CharField(max_length=20, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='instituicaoensino',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='ocupacao',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Ocupação'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
